import { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import {
  prepareSimulation,
  getPrepareStatus,
  getSimulationProfilesRealtime,
  getSimulationConfigRealtime,
} from '../../api/simulation';
import type { LogEntry } from '../../components/shared/log-viewer';
import { cx } from '../../utils/cx';

/* -------------------------------------------------------------------------- */
/*  Types                                                                      */
/* -------------------------------------------------------------------------- */

interface Step2Props {
  simulationId: string;
  projectData: any;
  graphData: any;
  systemLogs: LogEntry[];
  onGoBack: () => void;
  onNextStep: (params?: { maxRounds?: number }) => void;
  onAddLog: (msg: string) => void;
  onUpdateStatus: (status: string) => void;
}

interface Profile {
  username?: string;
  name?: string;
  profession?: string;
  bio?: string;
  interested_topics?: string[];
  entity_type?: string;
  age?: number;
  gender?: string;
  country?: string;
  mbti?: string;
  persona?: string;
  [key: string]: unknown;
}

interface TimeConfig {
  total_simulation_hours?: number;
  minutes_per_round?: number;
  agents_per_hour_min?: number;
  agents_per_hour_max?: number;
  peak_hours?: number[];
  peak_activity_multiplier?: number;
  work_hours?: number[];
  work_activity_multiplier?: number;
  morning_hours?: number[];
  morning_activity_multiplier?: number;
  off_peak_hours?: number[];
  off_peak_activity_multiplier?: number;
}

interface AgentConfig {
  agent_id: number;
  entity_name?: string;
  entity_type?: string;
  stance?: string;
  active_hours?: number[];
  posts_per_hour?: number;
  comments_per_hour?: number;
  response_delay_min?: number;
  response_delay_max?: number;
  activity_level?: number;
  sentiment_bias?: number;
  influence_weight?: number;
}

interface PlatformConfig {
  recency_weight?: number;
  popularity_weight?: number;
  relevance_weight?: number;
  viral_threshold?: number;
  echo_chamber_strength?: number;
}

interface EventConfig {
  narrative_direction?: string;
  hot_topics?: string[];
  initial_posts?: Array<{
    poster_type?: string;
    poster_agent_id?: number;
    content?: string;
  }>;
}

interface SimConfig {
  time_config?: TimeConfig;
  agent_configs?: AgentConfig[];
  twitter_config?: PlatformConfig;
  reddit_config?: PlatformConfig;
  event_config?: EventConfig;
  generation_reasoning?: string;
}

/* -------------------------------------------------------------------------- */
/*  Component                                                                  */
/* -------------------------------------------------------------------------- */

export function Step2EnvSetup({
  simulationId,
  projectData,
  graphData,
  systemLogs,
  onGoBack,
  onNextStep,
  onAddLog,
  onUpdateStatus,
}: Step2Props) {
  /* ---- state ---- */
  const [phase, setPhase] = useState(0);
  const [taskId, setTaskId] = useState<string | null>(null);
  const [prepareProgress, setPrepareProgress] = useState(0);
  const [profiles, setProfiles] = useState<Profile[]>([]);
  const [simulationConfig, setSimulationConfig] = useState<SimConfig | null>(null);
  const [selectedProfile, setSelectedProfile] = useState<Profile | null>(null);
  const [expectedTotal, setExpectedTotal] = useState<number | null>(null);
  const [entityTypes, setEntityTypes] = useState<string[]>([]);
  const [useCustomRounds, setUseCustomRounds] = useState(false);
  const [customMaxRounds, setCustomMaxRounds] = useState(40);

  /* ---- refs for mutable values across intervals ---- */
  const phaseRef = useRef(phase);
  phaseRef.current = phase;

  const taskIdRef = useRef(taskId);
  taskIdRef.current = taskId;

  const profilesRef = useRef(profiles);
  profilesRef.current = profiles;

  const expectedTotalRef = useRef(expectedTotal);
  expectedTotalRef.current = expectedTotal;

  const pollTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const profilesTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const configTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const lastLoggedMessageRef = useRef('');
  const lastLoggedProfileCountRef = useRef(0);
  const lastLoggedConfigStageRef = useRef('');

  const currentStageRef = useRef('');
  const logContentRef = useRef<HTMLDivElement>(null);

  /* keep stable ref for callbacks */
  const onAddLogRef = useRef(onAddLog);
  onAddLogRef.current = onAddLog;
  const onUpdateStatusRef = useRef(onUpdateStatus);
  onUpdateStatusRef.current = onUpdateStatus;
  const simulationIdRef = useRef(simulationId);
  simulationIdRef.current = simulationId;

  /* ---- derived ---- */
  const autoGeneratedRounds = useMemo(() => {
    if (!simulationConfig?.time_config) return null;
    const totalHours = simulationConfig.time_config.total_simulation_hours;
    const minutesPerRound = simulationConfig.time_config.minutes_per_round;
    if (!totalHours || !minutesPerRound) return null;
    const calculated = Math.floor((totalHours * 60) / minutesPerRound);
    return Math.max(calculated, 40);
  }, [simulationConfig]);

  const totalTopicsCount = useMemo(
    () => profiles.reduce((sum, p) => sum + (p.interested_topics?.length || 0), 0),
    [profiles],
  );

  const getAgentUsername = useCallback(
    (agentId: number) => {
      if (profiles.length > agentId && agentId >= 0) {
        return profiles[agentId]?.username || `agent_${agentId}`;
      }
      return `agent_${agentId}`;
    },
    [profiles],
  );

  /* ---- helpers ---- */
  const addLog = useCallback((msg: string) => {
    onAddLogRef.current(msg);
  }, []);

  const stopPolling = useCallback(() => {
    if (pollTimerRef.current) {
      clearInterval(pollTimerRef.current);
      pollTimerRef.current = null;
    }
  }, []);

  const stopProfilesPolling = useCallback(() => {
    if (profilesTimerRef.current) {
      clearInterval(profilesTimerRef.current);
      profilesTimerRef.current = null;
    }
  }, []);

  const stopConfigPolling = useCallback(() => {
    if (configTimerRef.current) {
      clearInterval(configTimerRef.current);
      configTimerRef.current = null;
    }
  }, []);

  /* ---- polling: profiles ---- */
  const fetchProfilesRealtime = useCallback(async () => {
    const simId = simulationIdRef.current;
    if (!simId) return;
    try {
      const res = await getSimulationProfilesRealtime(simId, 'reddit');
      if ((res as any).success && (res as any).data) {
        const data = (res as any).data;
        const newProfiles: Profile[] = (data.profiles || []).map((p: any) => ({
          ...p,
          interested_topics: Array.isArray(p.interested_topics)
            ? p.interested_topics
            : typeof p.interested_topics === 'string' && p.interested_topics
              ? p.interested_topics.split(',').map((t: string) => t.trim()).filter(Boolean)
              : [],
        }));
        setProfiles(newProfiles);

        if (data.total_expected) {
          setExpectedTotal(data.total_expected);
        }

        // extract entity types
        const types = new Set<string>();
        newProfiles.forEach((p) => {
          if (p.entity_type) types.add(p.entity_type);
        });
        setEntityTypes(Array.from(types));

        // log progress
        const currentCount = newProfiles.length;
        if (currentCount > 0 && currentCount !== lastLoggedProfileCountRef.current) {
          lastLoggedProfileCountRef.current = currentCount;
          const total = data.total_expected || expectedTotalRef.current || '?';
          const latest = newProfiles[currentCount - 1];
          const profileName = latest?.name || latest?.username || `Agent_${currentCount}`;
          if (currentCount === 1) {
            addLog('Generating agent personas...');
          }
          addLog(
            `→ Agent persona ${currentCount}/${total}: ${profileName} (${latest?.profession || 'Unknown profession'})`,
          );
          if (expectedTotalRef.current && currentCount >= expectedTotalRef.current) {
            addLog(`✓ All ${currentCount} agent personas generated`);
          }
        }
      }
    } catch (err) {
      console.warn('Failed to fetch profiles:', err);
    }
  }, [addLog]);

  /* ---- polling: config ---- */
  const fetchConfigRealtime = useCallback(async () => {
    const simId = simulationIdRef.current;
    if (!simId) return;
    try {
      const res = await getSimulationConfigRealtime(simId);
      if ((res as any).success && (res as any).data) {
        const data = (res as any).data;

        if (data.generation_stage && data.generation_stage !== lastLoggedConfigStageRef.current) {
          lastLoggedConfigStageRef.current = data.generation_stage;
          if (data.generation_stage === 'generating_profiles') {
            addLog('Generating agent persona config...');
          } else if (data.generation_stage === 'generating_config') {
            addLog('Calling LLM to generate simulation config parameters...');
          }
        }

        if (data.config_generated && data.config) {
          setSimulationConfig(data.config);
          addLog('✓ Simulation config generated');

          if (data.summary) {
            addLog(`  ├─ Agent count: ${data.summary.total_agents}`);
            addLog(`  ├─ Simulation duration: ${data.summary.simulation_hours} hrs`);
            addLog(`  ├─ Initial posts: ${data.summary.initial_posts_count}`);
            addLog(`  ├─ Hot topics: ${data.summary.hot_topics_count}`);
            addLog(
              `  └─ Platform config: Twitter ${data.summary.has_twitter_config ? '✓' : '✗'}, Reddit ${data.summary.has_reddit_config ? '✓' : '✗'}`,
            );
          }

          if (data.config.time_config) {
            const tc = data.config.time_config;
            addLog(
              `Time config: ${tc.minutes_per_round} min/round, ${Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round)} rounds total`,
            );
          }

          if (data.config.event_config?.narrative_direction) {
            const narrative = data.config.event_config.narrative_direction;
            addLog(
              `Narrative direction: ${narrative.length > 50 ? narrative.substring(0, 50) + '...' : narrative}`,
            );
          }

          stopConfigPolling();
          setPhase(4);
          addLog('✓ Environment setup complete, ready to simulate');
          onUpdateStatusRef.current('completed');
        }
      }
    } catch (err) {
      console.warn('Failed to fetch config:', err);
    }
  }, [addLog, stopConfigPolling]);

  const startConfigPolling = useCallback(() => {
    if (configTimerRef.current) return;
    configTimerRef.current = setInterval(fetchConfigRealtime, 2000);
  }, [fetchConfigRealtime]);

  /* ---- load already-prepared data ---- */
  const loadPreparedData = useCallback(async () => {
    setPhase(2);
    addLog('Loading existing config data...');

    await fetchProfilesRealtime();
    addLog(`Loaded ${profilesRef.current.length} agent personas`);

    try {
      const res = await getSimulationConfigRealtime(simulationIdRef.current);
      if ((res as any).success && (res as any).data) {
        const data = (res as any).data;
        if (data.config_generated && data.config) {
          setSimulationConfig(data.config);
          addLog('✓ Simulation config loaded successfully');
          if (data.summary) {
            addLog(`  ├─ Agent count: ${data.summary.total_agents}`);
            addLog(`  ├─ Simulation duration: ${data.summary.simulation_hours} hrs`);
            addLog(`  └─ Initial posts: ${data.summary.initial_posts_count}`);
          }
          addLog('✓ Environment setup complete, ready to simulate');
          setPhase(4);
          onUpdateStatusRef.current('completed');
        } else {
          addLog('Config generation in progress, polling...');
          startConfigPolling();
        }
      }
    } catch (err: any) {
      addLog(`Failed to load config: ${err.message}`);
      onUpdateStatusRef.current('error');
    }
  }, [addLog, fetchProfilesRealtime, startConfigPolling]);

  /* ---- polling: prepare status ---- */
  const pollPrepareStatus = useCallback(async () => {
    const tid = taskIdRef.current;
    const simId = simulationIdRef.current;
    if (!tid && !simId) return;

    try {
      const res = await getPrepareStatus({ task_id: tid!, simulation_id: simId });
      if ((res as any).success && (res as any).data) {
        const data = (res as any).data;
        setPrepareProgress(data.progress || 0);

        if (data.progress_detail) {
          const newStage = data.progress_detail.current_stage_name || '';
          currentStageRef.current = newStage;

          // phase transitions based on stage
          if (
            (newStage === 'Generating Agent Profiles' || newStage === 'generating_profiles') &&
            phaseRef.current < 1
          ) {
            setPhase(1);
          } else if (newStage === 'Generating Simulation Config' || newStage === 'generating_config') {
            if (phaseRef.current < 2) setPhase(2);
            if (!configTimerRef.current) {
              addLog('Generating dual-platform simulation config...');
              startConfigPolling();
            }
          } else if (newStage === 'Preparing Simulation Scripts' || newStage === 'copying_scripts') {
            if (phaseRef.current < 2) setPhase(2);
          }

          const detail = data.progress_detail;
          const logKey = `${detail.current_stage}-${detail.current_item}-${detail.total_items}`;
          if (logKey !== lastLoggedMessageRef.current && detail.item_description) {
            lastLoggedMessageRef.current = logKey;
            const stageInfo = `[${detail.stage_index}/${detail.total_stages}]`;
            if (detail.total_items > 0) {
              addLog(
                `${stageInfo} ${detail.current_stage_name}: ${detail.current_item}/${detail.total_items} - ${detail.item_description}`,
              );
            } else {
              addLog(`${stageInfo} ${detail.current_stage_name}: ${detail.item_description}`);
            }
          }
        } else if (data.message) {
          const match = data.message.match(/\[(\d+)\/(\d+)\]\s*([^:]+)/);
          if (match) {
            currentStageRef.current = match[3].trim();
          }
          if (data.message !== lastLoggedMessageRef.current) {
            lastLoggedMessageRef.current = data.message;
            addLog(data.message);
          }
        }

        if (data.status === 'completed' || data.status === 'ready' || data.already_prepared) {
          addLog('✓ Preparation complete');
          stopPolling();
          stopProfilesPolling();
          await loadPreparedData();
        } else if (data.status === 'failed') {
          addLog(`✗ Preparation failed: ${data.error || 'Unknown error'}`);
          stopPolling();
          stopProfilesPolling();
        }
      }
    } catch (err) {
      console.warn('Status polling failed:', err);
    }
  }, [addLog, stopPolling, stopProfilesPolling, startConfigPolling, loadPreparedData]);

  /* ---- kick off preparation ---- */
  const startPrepareSimulation = useCallback(async () => {
    if (!simulationIdRef.current) {
      addLog('Error: missing simulationId');
      onUpdateStatusRef.current('error');
      return;
    }

    setPhase(1);
    addLog(`Simulation instance created: ${simulationIdRef.current}`);
    addLog('Preparing simulation environment...');
    onUpdateStatusRef.current('processing');

    try {
      const res = await prepareSimulation({
        simulation_id: simulationIdRef.current,
        use_llm_for_profiles: true,
        parallel_profile_count: 5,
      });

      if ((res as any).success && (res as any).data) {
        const data = (res as any).data;

        if (data.already_prepared) {
          addLog('Detected existing completed preparation, reusing');
          await loadPreparedData();
          return;
        }

        setTaskId(data.task_id);
        taskIdRef.current = data.task_id;
        addLog('Preparation task started');
        addLog(`  └─ Task ID: ${data.task_id}`);

        if (data.expected_entities_count) {
          setExpectedTotal(data.expected_entities_count);
          expectedTotalRef.current = data.expected_entities_count;
          addLog(`Read ${data.expected_entities_count} entities from Zep graph`);
          if (data.entity_types?.length > 0) {
            addLog(`  └─ Entity types: ${data.entity_types.join(', ')}`);
          }
        }

        addLog('Polling preparation progress...');
        pollTimerRef.current = setInterval(pollPrepareStatus, 2000);
        profilesTimerRef.current = setInterval(fetchProfilesRealtime, 3000);
      } else {
        addLog(`Preparation failed: ${(res as any).error || 'Unknown error'}`);
        onUpdateStatusRef.current('error');
      }
    } catch (err: any) {
      addLog(`Preparation error: ${err.message}`);
      onUpdateStatusRef.current('error');
    }
  }, [addLog, loadPreparedData, pollPrepareStatus, fetchProfilesRealtime]);

  /* ---- mount / unmount ---- */
  useEffect(() => {
    if (simulationId) {
      addLog('Step 2: Environment setup initialized');
      startPrepareSimulation();
    }
    return () => {
      stopPolling();
      stopProfilesPolling();
      stopConfigPolling();
    };
    // Run only on mount
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /* ---- auto-scroll logs ---- */
  useEffect(() => {
    if (logContentRef.current) {
      logContentRef.current.scrollTop = logContentRef.current.scrollHeight;
    }
  }, [systemLogs]);

  /* ---- handlers ---- */
  const handleStartSimulation = useCallback(() => {
    const params: { maxRounds?: number } = {};
    if (useCustomRounds) {
      params.maxRounds = customMaxRounds;
      addLog(`Starting simulation with custom rounds: ${customMaxRounds}`);
    } else {
      addLog(`Starting simulation with auto-configured rounds: ${autoGeneratedRounds}`);
    }
    onNextStep(params);
  }, [useCustomRounds, customMaxRounds, autoGeneratedRounds, addLog, onNextStep]);

  const sliderPercent = useMemo(() => {
    if (!autoGeneratedRounds || autoGeneratedRounds <= 10) return 0;
    return ((customMaxRounds - 10) / (autoGeneratedRounds - 10)) * 100;
  }, [customMaxRounds, autoGeneratedRounds]);

  const recommendLeftPercent = useMemo(() => {
    if (!autoGeneratedRounds || autoGeneratedRounds <= 10) return 0;
    return ((40 - 10) / (autoGeneratedRounds - 10)) * 100;
  }, [autoGeneratedRounds]);

  /* ---- gender label ---- */
  const genderLabel = (g?: string) => {
    const map: Record<string, string> = { male: 'Male', female: 'Female', other: 'Other' };
    return (g && map[g]) || g || '-';
  };

  /* ---- total rounds computed ---- */
  const totalRounds = useMemo(() => {
    const tc = simulationConfig?.time_config;
    if (!tc?.total_simulation_hours || !tc?.minutes_per_round) return '-';
    return Math.floor((tc.total_simulation_hours * 60) / tc.minutes_per_round);
  }, [simulationConfig]);

  /* ========================================================================== */
  /*  RENDER                                                                     */
  /* ========================================================================== */

  return (
    <div className="flex h-full flex-col bg-brand-50 font-sans">
      <div className="flex-1 overflow-y-auto p-6 space-y-5">
        {/* ------------------------------------------------------------------ */}
        {/*  Step 01 - Simulation Instance                                      */}
        {/* ------------------------------------------------------------------ */}
        <div
          className={cx(
            'rounded-lg bg-white p-5 shadow-sm border transition-all duration-300',
            phase === 0 && 'border-brand-600 shadow-md shadow-brand-600/10',
            phase > 0 && 'border-brand-200',
            phase < 0 && 'border-brand-100',
          )}
        >
          {/* header */}
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  phase >= 0 ? 'text-brand-950' : 'text-brand-200',
                )}
              >
                01
              </span>
              <span className="text-sm font-semibold tracking-wide text-brand-950">
                Simulation Instance Init
              </span>
            </div>
            <div>
              {phase > 0 ? (
                <span className="rounded bg-green-100 px-2 py-1 text-[10px] font-semibold uppercase text-green-700">
                  Complete
                </span>
              ) : (
                <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
                  Initializing
                </span>
              )}
            </div>
          </div>

          {/* content */}
          <div>
            <p className="font-mono text-[10px] text-brand-400 mb-2">
              POST /api/simulation/create
            </p>
            <p className="text-xs text-brand-500 leading-relaxed mb-4">
              Create simulation instance, fetch world parameter templates
            </p>

            {simulationId && (
              <div className="rounded-md bg-brand-50 p-3 space-y-2">
                <InfoRow label="Project ID" value={projectData?.project_id} />
                <InfoRow label="Graph ID" value={projectData?.graph_id} />
                <InfoRow label="Simulation ID" value={simulationId} />
                <InfoRow label="Task ID" value={taskId || 'Async task complete'} />
              </div>
            )}
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/*  Step 02 - Agent Profiles                                           */}
        {/* ------------------------------------------------------------------ */}
        <div
          className={cx(
            'rounded-lg bg-white p-5 shadow-sm border transition-all duration-300',
            phase === 1 && 'border-brand-600 shadow-md shadow-brand-600/10',
            phase > 1 && 'border-brand-200',
            phase < 1 && 'border-brand-100',
          )}
        >
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  phase >= 1 ? 'text-brand-950' : 'text-brand-200',
                )}
              >
                02
              </span>
              <span className="text-sm font-semibold tracking-wide text-brand-950">
                Generate Agent Personas
              </span>
            </div>
            <div>
              {phase > 1 ? (
                <span className="rounded bg-green-100 px-2 py-1 text-[10px] font-semibold uppercase text-green-700">
                  Complete
                </span>
              ) : phase === 1 ? (
                <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
                  {prepareProgress}%
                </span>
              ) : (
                <span className="rounded bg-brand-100 px-2 py-1 text-[10px] font-semibold uppercase text-brand-400">
                  Waiting
                </span>
              )}
            </div>
          </div>

          <div>
            <p className="font-mono text-[10px] text-brand-400 mb-2">
              POST /api/simulation/prepare
            </p>
            <p className="text-xs text-brand-500 leading-relaxed mb-4">
              Automatically extract entities and relationships from the knowledge graph, initialize simulated individuals, and assign unique behaviors and memories based on real-world seeds
            </p>

            {/* Stats Grid */}
            {profiles.length > 0 && (
              <div className="grid grid-cols-3 gap-3 mb-4">
                <StatCard value={profiles.length} label="Current Agents" />
                <StatCard value={expectedTotal ?? '-'} label="Expected Total Agents" />
                <StatCard value={totalTopicsCount} label="Seed-linked Topics" />
              </div>
            )}

            {/* Profiles List */}
            {profiles.length > 0 && (
              <div>
                <div className="mb-2">
                  <span className="text-xs font-semibold text-brand-700">Generated Agent Personas</span>
                </div>
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                  {profiles.map((profile, idx) => (
                    <button
                      key={idx}
                      type="button"
                      className="rounded-lg border border-brand-100 bg-brand-50/50 p-3 text-left transition-all hover:border-brand-300 hover:shadow-sm"
                      onClick={() => setSelectedProfile(profile)}
                    >
                      <div className="flex items-baseline gap-2 mb-1">
                        <span className="text-sm font-semibold text-brand-950 truncate">
                          {profile.username || 'Unknown'}
                        </span>
                        <span className="text-[11px] text-brand-400 truncate">
                          @{profile.name || `agent_${idx}`}
                        </span>
                      </div>
                      <div className="mb-1">
                        <span className="text-[11px] text-brand-500">
                          {profile.profession || 'Unknown profession'}
                        </span>
                      </div>
                      <p className="text-[11px] text-brand-400 leading-relaxed line-clamp-2 mb-2">
                        {profile.bio || 'No bio available'}
                      </p>
                      {profile.interested_topics && profile.interested_topics.length > 0 && (
                        <div className="flex flex-wrap gap-1">
                          {profile.interested_topics.slice(0, 3).map((topic) => (
                            <span
                              key={topic}
                              className="rounded-full bg-brand-100 px-2 py-0.5 text-[10px] text-brand-600"
                            >
                              {topic}
                            </span>
                          ))}
                          {profile.interested_topics.length > 3 && (
                            <span className="text-[10px] text-brand-400">
                              +{profile.interested_topics.length - 3}
                            </span>
                          )}
                        </div>
                      )}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/*  Step 03 - Simulation Config                                        */}
        {/* ------------------------------------------------------------------ */}
        <div
          className={cx(
            'rounded-lg bg-white p-5 shadow-sm border transition-all duration-300',
            phase === 2 && 'border-brand-600 shadow-md shadow-brand-600/10',
            phase > 2 && 'border-brand-200',
            phase < 2 && 'border-brand-100',
          )}
        >
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  phase >= 2 ? 'text-brand-950' : 'text-brand-200',
                )}
              >
                03
              </span>
              <span className="text-sm font-semibold tracking-wide text-brand-950">
                Generate Dual-Platform Sim Config
              </span>
            </div>
            <div>
              {phase > 2 ? (
                <span className="rounded bg-green-100 px-2 py-1 text-[10px] font-semibold uppercase text-green-700">
                  Complete
                </span>
              ) : phase === 2 ? (
                <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
                  Generating
                </span>
              ) : (
                <span className="rounded bg-brand-100 px-2 py-1 text-[10px] font-semibold uppercase text-brand-400">
                  Waiting
                </span>
              )}
            </div>
          </div>

          <div>
            <p className="font-mono text-[10px] text-brand-400 mb-2">
              POST /api/simulation/prepare
            </p>
            <p className="text-xs text-brand-500 leading-relaxed mb-4">
              LLM
              Intelligently configure world time flow, recommendation algorithms, individual activity windows, posting frequency, event triggers, and more based on simulation requirements and real-world seeds
            </p>

            {simulationConfig && (
              <div className="space-y-4">
                {/* Time Config Grid */}
                <div className="space-y-3">
                  <div className="grid grid-cols-4 gap-3">
                    <ConfigItem
                      label="Sim Duration"
                      value={`${simulationConfig.time_config?.total_simulation_hours || '-'} hrs`}
                    />
                    <ConfigItem
                      label="Round Duration"
                      value={`${simulationConfig.time_config?.minutes_per_round || '-'} min`}
                    />
                    <ConfigItem label="Total Rounds" value={`${totalRounds} rounds`} />
                    <ConfigItem
                      label="Active/Hour"
                      value={`${simulationConfig.time_config?.agents_per_hour_min ?? '-'}-${simulationConfig.time_config?.agents_per_hour_max ?? '-'}`}
                    />
                  </div>

                  {/* Time Periods */}
                  <div className="grid grid-cols-2 gap-2">
                    <TimePeriod
                      label="Peak Hours"
                      hours={
                        simulationConfig.time_config?.peak_hours
                          ? simulationConfig.time_config.peak_hours
                              .map((h) => `${h}:00`)
                              .join(', ')
                          : '-'
                      }
                      multiplier={simulationConfig.time_config?.peak_activity_multiplier}
                    />
                    <TimePeriod
                      label="Work Hours"
                      hours={formatHoursRange(simulationConfig.time_config?.work_hours)}
                      multiplier={simulationConfig.time_config?.work_activity_multiplier}
                    />
                    <TimePeriod
                      label="Morning Hours"
                      hours={formatHoursRange(simulationConfig.time_config?.morning_hours)}
                      multiplier={simulationConfig.time_config?.morning_activity_multiplier}
                    />
                    <TimePeriod
                      label="Off-Peak Hours"
                      hours={formatHoursRange(simulationConfig.time_config?.off_peak_hours)}
                      multiplier={simulationConfig.time_config?.off_peak_activity_multiplier}
                    />
                  </div>
                </div>

                {/* Agent Configs */}
                <div>
                  <div className="flex items-center gap-2 mb-3">
                    <span className="text-xs font-semibold text-brand-700">Agent Config</span>
                    <span className="rounded bg-brand-100 px-1.5 py-0.5 text-[10px] font-semibold text-brand-600">
                      {simulationConfig.agent_configs?.length || 0}
                    </span>
                  </div>
                  <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                    {simulationConfig.agent_configs?.map((agent) => (
                      <div
                        key={agent.agent_id}
                        className="rounded-lg border border-brand-100 bg-brand-50/30 p-3 space-y-3"
                      >
                        {/* Card header */}
                        <div className="flex items-center justify-between">
                          <div className="flex items-center gap-2">
                            <span className="text-xs font-semibold text-brand-950">
                              Agent {agent.agent_id}
                            </span>
                            <span className="text-xs text-brand-500">{agent.entity_name}</span>
                          </div>
                          <div className="flex items-center gap-1.5">
                            <span className="rounded bg-brand-100 px-1.5 py-0.5 text-[10px] text-brand-600">
                              {agent.entity_type}
                            </span>
                            <span
                              className={cx(
                                'rounded px-1.5 py-0.5 text-[10px] font-medium',
                                agent.stance === 'positive' && 'bg-green-100 text-green-700',
                                agent.stance === 'negative' && 'bg-red-100 text-red-700',
                                agent.stance === 'neutral' && 'bg-gray-100 text-gray-600',
                                !['positive', 'negative', 'neutral'].includes(
                                  agent.stance || '',
                                ) && 'bg-brand-100 text-brand-600',
                              )}
                            >
                              {agent.stance}
                            </span>
                          </div>
                        </div>

                        {/* Activity Timeline */}
                        <div>
                          <span className="text-[10px] text-brand-400 mb-1 block">Active Hours</span>
                          <div className="flex gap-px">
                            {Array.from({ length: 24 }, (_, h) => (
                              <div
                                key={h}
                                title={`${h}:00`}
                                className={cx(
                                  'h-3 flex-1 rounded-sm transition-colors',
                                  agent.active_hours?.includes(h)
                                    ? 'bg-brand-600'
                                    : 'bg-brand-100',
                                )}
                              />
                            ))}
                          </div>
                          <div className="flex justify-between mt-0.5">
                            <span className="text-[9px] text-brand-300">0</span>
                            <span className="text-[9px] text-brand-300">6</span>
                            <span className="text-[9px] text-brand-300">12</span>
                            <span className="text-[9px] text-brand-300">18</span>
                            <span className="text-[9px] text-brand-300">24</span>
                          </div>
                        </div>

                        {/* Behavior Params */}
                        <div className="grid grid-cols-3 gap-2">
                          <ParamItem label="Posts/hr" value={agent.posts_per_hour} />
                          <ParamItem label="Comments/hr" value={agent.comments_per_hour} />
                          <ParamItem
                            label="Response Delay"
                            value={`${agent.response_delay_min}-${agent.response_delay_max}min`}
                          />
                        </div>
                        <div className="grid grid-cols-3 gap-2">
                          <div className="text-center">
                            <span className="block text-[10px] text-brand-400 mb-0.5">Activity</span>
                            <div className="flex items-center gap-1 justify-center">
                              <div className="h-1.5 w-10 rounded-full bg-brand-100 overflow-hidden">
                                <div
                                  className="h-full rounded-full bg-brand-600"
                                  style={{
                                    width: `${(agent.activity_level ?? 0) * 100}%`,
                                  }}
                                />
                              </div>
                              <span className="text-[11px] font-medium text-brand-700">
                                {((agent.activity_level ?? 0) * 100).toFixed(0)}%
                              </span>
                            </div>
                          </div>
                          <div className="text-center">
                            <span className="block text-[10px] text-brand-400 mb-0.5">
                              Sentiment Bias
                            </span>
                            <span
                              className={cx(
                                'text-[11px] font-medium',
                                (agent.sentiment_bias ?? 0) > 0
                                  ? 'text-green-600'
                                  : (agent.sentiment_bias ?? 0) < 0
                                    ? 'text-red-600'
                                    : 'text-brand-500',
                              )}
                            >
                              {(agent.sentiment_bias ?? 0) > 0 ? '+' : ''}
                              {agent.sentiment_bias?.toFixed(1)}
                            </span>
                          </div>
                          <div className="text-center">
                            <span className="block text-[10px] text-brand-400 mb-0.5">Influence</span>
                            <span className="text-[11px] font-semibold text-brand-700">
                              {agent.influence_weight?.toFixed(1)}
                            </span>
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Platform Config */}
                <div>
                  <div className="mb-3">
                    <span className="text-xs font-semibold text-brand-700">Recommendation Algorithm Config</span>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                    {simulationConfig.twitter_config && (
                      <PlatformCard
                        name="Platform 1: Feed / Timeline"
                        config={simulationConfig.twitter_config}
                      />
                    )}
                    {simulationConfig.reddit_config && (
                      <PlatformCard
                        name="Platform 2: Topics / Communities"
                        config={simulationConfig.reddit_config}
                      />
                    )}
                  </div>
                </div>

                {/* LLM Reasoning */}
                {simulationConfig.generation_reasoning && (
                  <div>
                    <div className="mb-3">
                      <span className="text-xs font-semibold text-brand-700">LLM Config Reasoning</span>
                    </div>
                    <div className="space-y-2">
                      {simulationConfig.generation_reasoning
                        .split('|')
                        .slice(0, 2)
                        .map((reason, idx) => (
                          <div key={idx} className="rounded-md bg-brand-50 p-3">
                            <p className="text-xs text-brand-600 leading-relaxed">
                              {reason.trim()}
                            </p>
                          </div>
                        ))}
                    </div>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/*  Step 04 - Orchestration                                            */}
        {/* ------------------------------------------------------------------ */}
        <div
          className={cx(
            'rounded-lg bg-white p-5 shadow-sm border transition-all duration-300',
            phase === 3 && 'border-brand-600 shadow-md shadow-brand-600/10',
            phase > 3 && 'border-brand-200',
            phase < 3 && 'border-brand-100',
          )}
        >
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  phase >= 3 ? 'text-brand-950' : 'text-brand-200',
                )}
              >
                04
              </span>
              <span className="text-sm font-semibold tracking-wide text-brand-950">
                Initial Activation Orchestration
              </span>
            </div>
            <div>
              {phase > 3 ? (
                <span className="rounded bg-green-100 px-2 py-1 text-[10px] font-semibold uppercase text-green-700">
                  Complete
                </span>
              ) : phase === 3 ? (
                <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
                  Orchestrating
                </span>
              ) : (
                <span className="rounded bg-brand-100 px-2 py-1 text-[10px] font-semibold uppercase text-brand-400">
                  Waiting
                </span>
              )}
            </div>
          </div>

          <div>
            <p className="font-mono text-[10px] text-brand-400 mb-2">
              POST /api/simulation/prepare
            </p>
            <p className="text-xs text-brand-500 leading-relaxed mb-4">
              Auto-generate initial activation events and hot topics based on narrative direction to bootstrap the simulated world
            </p>

            {simulationConfig?.event_config && (
              <div className="space-y-4">
                {/* Narrative Direction */}
                <div className="rounded-lg border border-orange-200 bg-gradient-to-br from-orange-50 to-amber-50 p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z"
                        stroke="url(#compass_grad)"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <path
                        d="M16.24 7.76L14.12 14.12L7.76 16.24L9.88 9.88L16.24 7.76Z"
                        fill="url(#compass_grad)"
                        stroke="url(#compass_grad)"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                      <defs>
                        <linearGradient
                          id="compass_grad"
                          x1="2"
                          y1="2"
                          x2="22"
                          y2="22"
                          gradientUnits="userSpaceOnUse"
                        >
                          <stop stopColor="#FF5722" />
                          <stop offset="1" stopColor="#FF9800" />
                        </linearGradient>
                      </defs>
                    </svg>
                    <span className="text-xs font-semibold text-orange-700">Narrative Direction</span>
                  </div>
                  <p className="text-xs text-orange-800 leading-relaxed">
                    {simulationConfig.event_config.narrative_direction}
                  </p>
                </div>

                {/* Hot Topics */}
                <div>
                  <span className="text-xs font-semibold text-brand-700 mb-2 block">
                    Initial Hot Topics
                  </span>
                  <div className="flex flex-wrap gap-2">
                    {simulationConfig.event_config.hot_topics?.map((topic) => (
                      <span
                        key={topic}
                        className="rounded-full bg-brand-100 px-3 py-1 text-xs font-medium text-brand-700"
                      >
                        # {topic}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Initial Posts Timeline */}
                <div>
                  <span className="text-xs font-semibold text-brand-700 mb-3 block">
                    Initial Activation Sequence ({simulationConfig.event_config.initial_posts?.length || 0})
                  </span>
                  <div className="relative pl-4 border-l-2 border-brand-200 space-y-4">
                    {simulationConfig.event_config.initial_posts?.map((post, idx) => (
                      <div key={idx} className="relative">
                        <div className="absolute -left-[21px] top-1 h-2.5 w-2.5 rounded-full bg-brand-600 ring-2 ring-white" />
                        <div className="rounded-lg bg-brand-50/50 p-3">
                          <div className="flex items-center gap-2 mb-1.5">
                            <span className="rounded bg-brand-200 px-1.5 py-0.5 text-[10px] font-medium text-brand-700">
                              {post.poster_type}
                            </span>
                            <span className="text-[11px] font-medium text-brand-700">
                              Agent {post.poster_agent_id}
                            </span>
                            <span className="text-[11px] text-brand-400">
                              @{getAgentUsername(post.poster_agent_id ?? 0)}
                            </span>
                          </div>
                          <p className="text-xs text-brand-600 leading-relaxed">{post.content}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {/* ------------------------------------------------------------------ */}
        {/*  Step 05 - Ready                                                    */}
        {/* ------------------------------------------------------------------ */}
        <div
          className={cx(
            'rounded-lg bg-white p-5 shadow-sm border transition-all duration-300',
            phase >= 4 && 'border-brand-600 shadow-md shadow-brand-600/10',
            phase < 4 && 'border-brand-100',
          )}
        >
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <span
                className={cx(
                  'font-mono text-xl font-bold',
                  phase >= 4 ? 'text-brand-950' : 'text-brand-200',
                )}
              >
                05
              </span>
              <span className="text-sm font-semibold tracking-wide text-brand-950">Ready</span>
            </div>
            <div>
              {phase >= 4 ? (
                <span className="rounded bg-brand-600 px-2 py-1 text-[10px] font-semibold uppercase text-white">
                  In Progress
                </span>
              ) : (
                <span className="rounded bg-brand-100 px-2 py-1 text-[10px] font-semibold uppercase text-brand-400">
                  Waiting
                </span>
              )}
            </div>
          </div>

          <div>
            <p className="font-mono text-[10px] text-brand-400 mb-2">
              POST /api/simulation/start
            </p>
            <p className="text-xs text-brand-500 leading-relaxed mb-4">
              Simulation environment is ready. You may begin the simulation.
            </p>

            {/* Rounds Config */}
            {simulationConfig && autoGeneratedRounds && (
              <div className="rounded-lg border border-brand-100 bg-brand-50/30 p-4 mb-4 space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <span className="text-xs font-semibold text-brand-950 block mb-1">
                      Simulation Round Settings
                    </span>
                    <span className="text-[11px] text-brand-500">
                      nVision auto-planned simulation of{' '}
                      <span className="font-semibold text-brand-700">
                        {simulationConfig.time_config?.total_simulation_hours || '-'}
                      </span>{' '}
                      hours; each round represents{' '}
                      <span className="font-semibold text-brand-700">
                        {simulationConfig.time_config?.minutes_per_round || '-'}
                      </span>{' '}
                      minutes of elapsed time
                    </span>
                  </div>
                  <label className="flex items-center gap-2 cursor-pointer select-none">
                    <div className="relative">
                      <input
                        type="checkbox"
                        className="sr-only peer"
                        checked={useCustomRounds}
                        onChange={(e) => setUseCustomRounds(e.target.checked)}
                      />
                      <div className="h-5 w-9 rounded-full bg-brand-200 peer-checked:bg-brand-600 transition-colors" />
                      <div className="absolute left-0.5 top-0.5 h-4 w-4 rounded-full bg-white shadow transition-transform peer-checked:translate-x-4" />
                    </div>
                    <span className="text-[11px] text-brand-600 font-medium">Custom</span>
                  </label>
                </div>

                {useCustomRounds ? (
                  <div className="space-y-3">
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-bold text-brand-950">{customMaxRounds}</span>
                      <span className="text-sm text-brand-400"> rounds</span>
                    </div>
                    <p className="text-[11px] text-brand-400">
                      For 100 agents: estimated time ~ {Math.round(customMaxRounds * 0.6)} min
                    </p>

                    <div className="space-y-1">
                      <input
                        type="range"
                        min={10}
                        max={autoGeneratedRounds}
                        step={5}
                        value={customMaxRounds}
                        onChange={(e) => setCustomMaxRounds(Number(e.target.value))}
                        className="w-full h-1.5 rounded-full appearance-none cursor-pointer bg-brand-200 accent-brand-600"
                        style={
                          {
                            background: `linear-gradient(to right, var(--color-brand-600) 0%, var(--color-brand-600) ${sliderPercent}%, var(--color-brand-200) ${sliderPercent}%, var(--color-brand-200) 100%)`,
                          } as React.CSSProperties
                        }
                      />
                      <div className="relative flex justify-between text-[10px] text-brand-400">
                        <span>10</span>
                        <button
                          type="button"
                          className={cx(
                            'absolute text-[10px] transition-colors',
                            customMaxRounds === 40
                              ? 'text-brand-700 font-semibold'
                              : 'text-brand-400 hover:text-brand-600',
                          )}
                          style={{ left: `calc(${recommendLeftPercent}% - 30px)` }}
                          onClick={() => setCustomMaxRounds(40)}
                        >
                          40 (Recommended)
                        </button>
                        <span>{autoGeneratedRounds}</span>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div className="flex items-center gap-4 rounded-lg bg-white p-3 border border-brand-100">
                    <div className="flex items-baseline gap-1">
                      <span className="text-3xl font-bold text-brand-950">
                        {autoGeneratedRounds}
                      </span>
                      <span className="text-sm text-brand-400"> rounds</span>
                    </div>
                    <div className="flex-1 space-y-1">
                      <div className="flex items-center gap-1 text-[11px] text-brand-500">
                        <svg
                          width="12"
                          height="12"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <circle cx="12" cy="12" r="10" />
                          <polyline points="12 6 12 12 16 14" />
                        </svg>
                        For 100 agents: estimated time {Math.round(autoGeneratedRounds * 0.6)} min
                      </div>
                      <button
                        type="button"
                        className="text-[11px] text-brand-600 hover:text-brand-700 font-medium transition-colors text-left"
                        onClick={() => setUseCustomRounds(true)}
                      >
                        For first runs, we strongly recommend switching to &apos;Custom mode&apos; to reduce round count for a quick preview and lower error risk
                        →
                      </button>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Action Buttons */}
            <div className="flex items-center gap-3">
              <button
                type="button"
                className="rounded-md border border-brand-200 bg-white px-5 py-2.5 text-sm font-semibold text-brand-700 transition-colors hover:bg-brand-50"
                onClick={onGoBack}
              >
                ← Back to Graph Build
              </button>
              <button
                type="button"
                disabled={phase < 4}
                className={cx(
                  'rounded-md px-5 py-2.5 text-sm font-semibold transition-colors',
                  phase >= 4
                    ? 'bg-brand-950 text-white hover:bg-brand-800 cursor-pointer'
                    : 'bg-brand-200 text-brand-400 cursor-not-allowed',
                )}
                onClick={handleStartSimulation}
              >
                Start Dual-World Parallel Simulation →
              </button>
            </div>
          </div>
        </div>
      </div>

      {/* -------------------------------------------------------------------- */}
      {/*  Profile Detail Modal                                                 */}
      {/* -------------------------------------------------------------------- */}
      {selectedProfile && (
        <div
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 backdrop-blur-sm"
          onClick={(e) => {
            if (e.target === e.currentTarget) setSelectedProfile(null);
          }}
        >
          <div className="relative w-full max-w-lg max-h-[85vh] overflow-y-auto rounded-2xl bg-white shadow-2xl">
            {/* Modal Header */}
            <div className="sticky top-0 z-10 flex items-center justify-between bg-white border-b border-brand-100 px-6 py-4">
              <div>
                <div className="flex items-baseline gap-2 mb-0.5">
                  <span className="text-base font-bold text-brand-950">
                    {selectedProfile.username}
                  </span>
                  <span className="text-sm text-brand-400">@{selectedProfile.name}</span>
                </div>
                <span className="text-xs text-brand-500">{selectedProfile.profession}</span>
              </div>
              <button
                type="button"
                className="flex h-8 w-8 items-center justify-center rounded-full text-brand-400 hover:bg-brand-100 hover:text-brand-700 transition-colors text-xl"
                onClick={() => setSelectedProfile(null)}
              >
                ×
              </button>
            </div>

            <div className="px-6 py-4 space-y-5">
              {/* Basic Info Grid */}
              <div className="grid grid-cols-4 gap-3">
                <ModalInfoItem
                  label="Apparent Age"
                  value={selectedProfile.age ? `${selectedProfile.age}` : '-'}
                />
                <ModalInfoItem
                  label="Apparent Gender"
                  value={genderLabel(selectedProfile.gender)}
                />
                <ModalInfoItem label="Country/Region" value={selectedProfile.country || '-'} />
                <ModalInfoItem
                  label="Apparent MBTI"
                  value={selectedProfile.mbti || '-'}
                  isMbti
                />
              </div>

              {/* Bio */}
              <div>
                <span className="text-[11px] font-semibold text-brand-400 uppercase tracking-wider block mb-1.5">
                  Persona Summary
                </span>
                <p className="text-xs text-brand-700 leading-relaxed">
                  {selectedProfile.bio || 'No bio available'}
                </p>
              </div>

              {/* Interested Topics */}
              {selectedProfile.interested_topics &&
                selectedProfile.interested_topics.length > 0 && (
                  <div>
                    <span className="text-[11px] font-semibold text-brand-400 uppercase tracking-wider block mb-1.5">
                      Seed-linked Topics
                    </span>
                    <div className="flex flex-wrap gap-1.5">
                      {selectedProfile.interested_topics.map((topic) => (
                        <span
                          key={topic}
                          className="rounded-full bg-brand-100 px-2.5 py-1 text-[11px] text-brand-600"
                        >
                          {topic}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

              {/* Persona */}
              {selectedProfile.persona && (
                <div>
                  <span className="text-[11px] font-semibold text-brand-400 uppercase tracking-wider block mb-2">
                    Detailed Persona Background
                  </span>

                  {/* Persona Dimensions */}
                  <div className="grid grid-cols-2 gap-2 mb-3">
                    <DimensionCard title="Full Event Experience" desc="Complete behavioral trajectory in this event" />
                    <DimensionCard title="Behavioral Profile" desc="Experience summary and behavioral style preferences" />
                    <DimensionCard title="Unique Memory Imprint" desc="Memories formed from real-world seeds" />
                    <DimensionCard title="Social Network" desc="Individual links and interaction graph" />
                  </div>

                  <div className="rounded-lg bg-brand-50 p-3">
                    <p className="text-xs text-brand-600 leading-relaxed whitespace-pre-wrap">
                      {selectedProfile.persona}
                    </p>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* -------------------------------------------------------------------- */}
      {/*  System Logs                                                          */}
      {/* -------------------------------------------------------------------- */}
      <div className="border-t border-brand-200 bg-brand-950 text-brand-50">
        <div className="flex items-center justify-between px-4 py-2 border-b border-brand-800">
          <span className="text-[10px] font-semibold uppercase tracking-widest text-brand-400">
            System Dashboard
          </span>
          <span className="font-mono text-[10px] text-brand-500">
            {simulationId || 'NO_SIMULATION'}
          </span>
        </div>
        <div ref={logContentRef} className="h-32 overflow-y-auto px-4 py-2 space-y-0.5">
          {systemLogs.map((log, idx) => (
            <div key={idx} className="flex gap-2 text-[11px] font-mono leading-relaxed">
              <span className="text-brand-500 shrink-0">{log.timestamp}</span>
              <span className="text-brand-300">{log.message}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}

/* ========================================================================== */
/*  Sub-components                                                             */
/* ========================================================================== */

function InfoRow({ label, value }: { label: string; value?: string | null }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-[11px] text-brand-400">{label}</span>
      <span className="font-mono text-[11px] text-brand-700">{value || '-'}</span>
    </div>
  );
}

function StatCard({ value, label }: { value: string | number; label: string }) {
  return (
    <div className="rounded-lg bg-brand-50 p-3 text-center">
      <span className="block text-lg font-bold text-brand-950">{value}</span>
      <span className="text-[10px] text-brand-400">{label}</span>
    </div>
  );
}

function ConfigItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md bg-brand-50 p-2.5 text-center">
      <span className="block text-[10px] text-brand-400 mb-0.5">{label}</span>
      <span className="text-xs font-semibold text-brand-800">{value}</span>
    </div>
  );
}

function TimePeriod({
  label,
  hours,
  multiplier,
}: {
  label: string;
  hours: string;
  multiplier?: number;
}) {
  return (
    <div className="flex items-center justify-between rounded-md bg-brand-50 px-3 py-2">
      <span className="text-[11px] font-medium text-brand-600">{label}</span>
      <span className="text-[11px] text-brand-500">{hours}</span>
      {multiplier != null && (
        <span className="text-[11px] font-semibold text-brand-700">x{multiplier}</span>
      )}
    </div>
  );
}

function ParamItem({ label, value }: { label: string; value?: string | number | null }) {
  return (
    <div className="text-center">
      <span className="block text-[10px] text-brand-400 mb-0.5">{label}</span>
      <span className="text-[11px] font-medium text-brand-700">{value ?? '-'}</span>
    </div>
  );
}

function PlatformCard({ name, config }: { name: string; config: PlatformConfig }) {
  return (
    <div className="rounded-lg border border-brand-100 p-3">
      <div className="mb-2">
        <span className="text-xs font-semibold text-brand-700">{name}</span>
      </div>
      <div className="space-y-1.5">
        <PlatformRow label="Recency Weight" value={config.recency_weight} />
        <PlatformRow label="Popularity Weight" value={config.popularity_weight} />
        <PlatformRow label="Relevance Weight" value={config.relevance_weight} />
        <PlatformRow label="Viral Threshold" value={config.viral_threshold} />
        <PlatformRow label="Echo Chamber Strength" value={config.echo_chamber_strength} />
      </div>
    </div>
  );
}

function PlatformRow({ label, value }: { label: string; value?: number }) {
  return (
    <div className="flex items-center justify-between">
      <span className="text-[11px] text-brand-500">{label}</span>
      <span className="text-[11px] font-medium text-brand-700">{value ?? '-'}</span>
    </div>
  );
}

function ModalInfoItem({
  label,
  value,
  isMbti,
}: {
  label: string;
  value: string;
  isMbti?: boolean;
}) {
  return (
    <div className="rounded-md bg-brand-50 p-2 text-center">
      <span className="block text-[10px] text-brand-400 mb-0.5">{label}</span>
      <span
        className={cx('text-xs font-semibold', isMbti ? 'text-brand-600' : 'text-brand-800')}
      >
        {value}
      </span>
    </div>
  );
}

function DimensionCard({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="rounded-md border border-brand-100 bg-white p-2.5">
      <span className="block text-[11px] font-semibold text-brand-700 mb-0.5">{title}</span>
      <span className="text-[10px] text-brand-400">{desc}</span>
    </div>
  );
}

/* ========================================================================== */
/*  Utilities                                                                  */
/* ========================================================================== */

function formatHoursRange(hours?: number[]): string {
  if (!hours || hours.length === 0) return '-';
  return `${hours[0]}:00-${hours[hours.length - 1]}:00`;
}
